### ISSUE TITLE
Error color contrast is hard to read

### ISSUE THREAD

**Issue by PiDelport** [ntls-io/nautilus-wallet#172]
The current shade of red on blue is hard to read, especially for colour blindness.

### Context

- https://github.com/ntls-io/nautilus-wallet/pull/167#pullrequestreview-946744693
- [Chromatic story comment](https://www.chromatic.com/test?appId=619e482ab3e38b003a063523&id=625ec6443ef305003a3b6043)

### Tasks

We should:

- [x] Audit and list the places in the UI where we currently have error (red) text
- [x] See what the WCAG contrast levels are for those, and determine what level we want to aim for (AA, AAA)
- [ ] Determine if WCAG has any specific guidance for colour blindness, for this?

**Comment by PiDelport** [comment]
A useful resource for this: https://webaim.org/resources/contrastchecker/

**Comment by PiDelport** [comment]
@IscoRuta98: Want to take a look at this?
